title: Yu-Chan Jimmy Chien
logo: "/images/logo.png"
description: >
  <br>
  I am a full-stack data science engineer and analyst specializing in translating complex business requirements into scalable data solutions.
  I hold a Master of Science in Computational Analysis and Public Policy from the University of Chicago.
  <br>

  <br>
  With over two years of experience collaborating across cross-functional teams, including Client Delivery, Product, Marketing, Publishing, Data, and IT, I own end-to-end analytics pipelines, data models, and reporting infrastructure across AWS and GCP.
  Acting as an internal consultant, I partner with business stakeholders to translate strategic requirements into self-service frameworks, scalable metrics, and automated Power BI ecosystems.
  <br>

  I am passionate about leveraging data science and software engineering to drive positive social impacts.
  Currently, I am self-studying core fields of modern computing architectures, including distributed systems, parallel programming, and cloud computing.
  Below is the roadmap documenting my learning journey in these fields 👇


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-35FELT9N8M 
